Remove overzealous ::template.
::template may only be used where explicit template arguments are supplied in this context, causing a build failure on macOS 16.5.1:

```console
/Users/vcpkg/Data/b/cpprealm/src/v2.2.0-f80d578acb.clean/include/cpprealm/schema.hpp:256:67: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  256 |                         auto ptr = managed<Class, void>::template unmanaged_to_managed_pointer(property.ptr);
      |                                                                   ^
/Users/vcpkg/Data/b/cpprealm/src/v2.2.0-f80d578acb.clean/include/cpprealm/schema.hpp:266:67: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  266 |                         auto ptr = managed<Class, void>::template unmanaged_to_managed_pointer(property.ptr);
      |                                                                   ^
```